export const FETCH_REQUEST= "FETCH_REQUEST" 
export const FETCH_REQUEST_SUCCESS= "FETCH_REQUEST_SUCCESS" 
export const FETCH_REQUEST_FAILURE= "FETCH_REQUEST_FAILURE" 

export const GET_SINGLE_PRODUCT_REQUEST= "GET_SINGLE_PRODUCT_REQUEST"
export const GET_SINGLE_PRODUCT_SUCCESS= "GET_SINGLE_PRODUCT_SUCCESS"
export const GET_SINGLE_PRODUCT_FAILURE= "GET_SINGLE_PRODUCT_FAILURE" 


export const GET_CART_REQUEST= "GET_CART_REQUEST"
export const GET_CART_SUCCESS= "GET_CART_SUCCESS"
export const GET_CART_FAILURE= "GET_CART_FAILURE" 




export const FETCH_CART_REQUEST= "FETCH_CART_REQUEST"
export const FETCH_CART_SUCCESS= "FETCH_CART_SUCCESS"
export const FETCH_CART_FAILURE= "FETCH_CART_FAILURE" 



export const DELETE_CART_REQUEST= "DELETE_CART_REQUEST"
export const DELETE_CART_SUCCESS= "DELETE_CART_SUCCESS"
export const DELETE_CART_FAILURE= "DELETE_CART_FAILURE" 